# 
# Do not Edit! Generated by:
# spectacle version 0.13~pre
# 
# >> macros
# << macros

Name:       xorg-x11-proto-renderproto
Summary:    X.Org X11 Protocol renderproto
Version:    0.11
Release:    0
Group:      Development/System
License:    MIT
URL:        http://www.x.org
Source0:    http://xorg.freedesktop.org/releases/individual/proto/renderproto-%{version}.tar.bz2
Source100:  xorg-x11-proto-renderproto.yaml
Provides:   renderproto

BuildRoot:  %{_tmppath}/%{name}-%{version}-build

%description
Description: %{summary}



%prep
%setup -q -n renderproto-%{version}
# >> setup
# << setup

%build
# >> build pre
# << build pre

%configure --disable-static \
    --libdir=%{_datadir}

# Call make instruction with smp support
make %{?jobs:-j%jobs}

# >> build post
# << build post
%install
rm -rf %{buildroot}
# >> install pre
# << install pre
%make_install

# >> install post
# << install post

%clean
rm -rf %{buildroot}






%files
%defattr(-,root,root,-)
# >> files
%{_datadir}/pkgconfig/renderproto.pc
%{_includedir}/X11/extensions/renderproto.h
%{_includedir}/X11/extensions/render.h
%doc %{_datadir}/doc/renderproto
# << files


